using System.Collections.Generic;

namespace Npgsql
{
    public class SqlColumnInfo
    {
        public string Name { get; }
        public bool IsBool { get; set; }

        public SqlColumnInfo(string name)
        {
            Name = name;
        }
    } 

    public class CapitalisationHelper
    {
        #region Table/col names

        List<SqlColumnInfo> _objectInfo = new List<SqlColumnInfo>
        {
            new SqlColumnInfo("__MigrationHistory"),
            new SqlColumnInfo("Accepted"),
            new SqlColumnInfo("AcceptedDate"),
            new SqlColumnInfo("AcceptedIp"),
            new SqlColumnInfo("AccountantName"),
            new SqlColumnInfo("ActionFilter"),
            new SqlColumnInfo("ActionRequired"),
            new SqlColumnInfo("Actions"),
            new SqlColumnInfo("ActiveEnd"),
            new SqlColumnInfo("AddedByUser_UserId"),
            new SqlColumnInfo("AddedByUser_UserId1"),
            new SqlColumnInfo("AdditionalProductFeePaymentType"),
            new SqlColumnInfo("Address"),
            new SqlColumnInfo("AddressBeingRefereedId"),
            new SqlColumnInfo("AddressContacts"),
            new SqlColumnInfo("AddressId"),
            new SqlColumnInfo("AddressLine1"),
            new SqlColumnInfo("AddressLine2"),
            new SqlColumnInfo("AddressMatchType"),
            new SqlColumnInfo("AddressType"),
            new SqlColumnInfo("AdminOrganiseEpc"),
            new SqlColumnInfo("AdministratorReference"),
            new SqlColumnInfo("AdminRemoved"),
            new SqlColumnInfo("AdminTaskId"),
            new SqlColumnInfo("AdminTasks"),
            new SqlColumnInfo("AdminTaskTypeDiscriminator"),
            new SqlColumnInfo("AdultsInProperty"),
            new SqlColumnInfo("AdvertisingAdditionalText"),
            new SqlColumnInfo("AdvertisingAdditionalTextOverride"),
            new SqlColumnInfo("AdvertListingStatus"),
            new SqlColumnInfo("AdvertUrl"),
            new SqlColumnInfo("Advertisement"),
            new SqlColumnInfo("AgencySagepayAccount"),
            new SqlColumnInfo("AgentApprovesAllCreditChecks"),
            new SqlColumnInfo("AgentPerformsCompliance"),
            new SqlColumnInfo("AgentRef"),
            new SqlColumnInfo("AgreementDeadline"),
            new SqlColumnInfo("AgreementDownloaded"),
            new SqlColumnInfo("AgreementResendDate"),
            new SqlColumnInfo("AgreementSigningType"),
            new SqlColumnInfo("AgreementStatus"),
            new SqlColumnInfo("AgreementType"),
            new SqlColumnInfo("AgreementZoneType"),
            new SqlColumnInfo("AlarmCode"),
            new SqlColumnInfo("AlertDate"),
            new SqlColumnInfo("AllowCompanyLets") {IsBool = true},
            new SqlColumnInfo("AllowDocuSignBypass"),
            new SqlColumnInfo("AllowFlatfairInsuranceScheme"),
            new SqlColumnInfo("AllowInterest"),
            new SqlColumnInfo("AllowLandlordsToRejectPostReferencing"),
            new SqlColumnInfo("AllowMarketingWithUnconfirmedLandlord"),
            new SqlColumnInfo("AllowMultiplePurchases"),
            new SqlColumnInfo("AllowMultiplePurchasesOverride"),
            new SqlColumnInfo("AllowNonAgentLandlordsToViewAllDocs"){IsBool = true},
            new SqlColumnInfo("AllowPartialMatches"),
            new SqlColumnInfo("AllowQuote"),
            new SqlColumnInfo("AllowReferenceBypassOptions"),
            new SqlColumnInfo("AllRequiredDocumentsPresent"),
            new SqlColumnInfo("AlternativeSupplierData_SupplierId"),
            new SqlColumnInfo("AlternativeSupplierDataId"),
            new SqlColumnInfo("Amount"),
            new SqlColumnInfo("Application"),
            new SqlColumnInfo("ApplicationId"),
            new SqlColumnInfo("ApplicationPrivateKey"),
            new SqlColumnInfo("ApplicationSettingId"),
            new SqlColumnInfo("ApplicationSettings"),
            new SqlColumnInfo("ApplicationType"),
            new SqlColumnInfo("ApplicationUser"),
            new SqlColumnInfo("ApplicationUserId"),
            new SqlColumnInfo("AppliedType"),
            new SqlColumnInfo("AppsApiKey"),
            new SqlColumnInfo("ArchivePassword"),
            new SqlColumnInfo("AreasToBeCleaned"),
            new SqlColumnInfo("AssignedOrganisationId"),
            new SqlColumnInfo("AssigneeId"),
            new SqlColumnInfo("AssociationId"),
            new SqlColumnInfo("AuditLog"),
            new SqlColumnInfo("AuditLogId"),
            new SqlColumnInfo("AuthenticationFailureIntervalCount"),
            new SqlColumnInfo("AuthenticationFailureTotalCount"),
            new SqlColumnInfo("AuthorId"),
            new SqlColumnInfo("AuthoriseDocusignAgreements"),
            new SqlColumnInfo("AwaitingAuthorisation"){IsBool = true},
            new SqlColumnInfo("AwaitingChangeOfSharersAgreement"),
            new SqlColumnInfo("AwaitingEarlyTerminationAgreement"),
            new SqlColumnInfo("AwaitingRegistration"),
            new SqlColumnInfo("AwaitingRenewalAgreement"),
            new SqlColumnInfo("B2CDefaultLetOnlyService"),
            new SqlColumnInfo("B2CTenantInviteOptions"),
            new SqlColumnInfo("Balcony"),
            new SqlColumnInfo("BankAccountId"),
            new SqlColumnInfo("BankAccounts"),
            new SqlColumnInfo("BankAccountType"),
            new SqlColumnInfo("BankAddressLine1"),
            new SqlColumnInfo("BankAddressLine2"),
            new SqlColumnInfo("BankAuthCode"),
            new SqlColumnInfo("BankCity"),
            new SqlColumnInfo("BankCountry"),
            new SqlColumnInfo("BankCounty"),
            new SqlColumnInfo("BankDetails"),
            new SqlColumnInfo("BankPaymentType"),
            new SqlColumnInfo("BankPostcode"),
            new SqlColumnInfo("Bankruptcy"),
            new SqlColumnInfo("BatchTaskId"),
            new SqlColumnInfo("BatchTaskSettings"),
            new SqlColumnInfo("BillingAddressId"),
            new SqlColumnInfo("BlockDocumentCentreForUnregisteredUsers"),
            new SqlColumnInfo("BookedDate"),
            new SqlColumnInfo("BookingConfirmedDate"),
            new SqlColumnInfo("ByPassAdvertVerification"),
            new SqlColumnInfo("BypassReferencingForms"),
            new SqlColumnInfo("BypassReferencingProvider"),
            new SqlColumnInfo("C123ApiKey"),
            new SqlColumnInfo("C123ApiToken"),
            new SqlColumnInfo("C123User"),
            new SqlColumnInfo("CallCreditCreditPassScore"),
            new SqlColumnInfo("CallCreditCreditPassScoreOverride"),
            new SqlColumnInfo("CanAccessFeeSchedule") {IsBool = true},
            new SqlColumnInfo("CanAffordRent"){IsBool = true},
            new SqlColumnInfo("CanBePrivate"){IsBool = true},
            new SqlColumnInfo("Cancelled"),
            new SqlColumnInfo("CancelledDate"),
            new SqlColumnInfo("CanDiscloseDataToThirdParties"),
            new SqlColumnInfo("CanGuarantorAffordRent"),
            new SqlColumnInfo("Caption"),
            new SqlColumnInfo("CardPaymentType"),
            new SqlColumnInfo("CardType"),
            new SqlColumnInfo("Category"),
            new SqlColumnInfo("CcjAmount"),
            new SqlColumnInfo("CcjCount"),
            new SqlColumnInfo("CcjOutstandingAmount"),
            new SqlColumnInfo("CcjOutstandingCount"),
            new SqlColumnInfo("ChargeType"),
            new SqlColumnInfo("ChargeTypeOverride"),
            new SqlColumnInfo("ChasedDate"),
            new SqlColumnInfo("ChildrenInProperty"),
            new SqlColumnInfo("City"),
            new SqlColumnInfo("ClientIpAddress"),
            new SqlColumnInfo("ClosedDate"),
            new SqlColumnInfo("Code"),
            new SqlColumnInfo("ColumnName"),
            new SqlColumnInfo("Comments"),
            new SqlColumnInfo("CompanyAddress") {IsBool = true},
            new SqlColumnInfo("CompanyEmail"),
            new SqlColumnInfo("CompanyName"),
            new SqlColumnInfo("CompanyNumber"),
            new SqlColumnInfo("CompanyReferenceId"),
            new SqlColumnInfo("CompanyReferences"),
            new SqlColumnInfo("CompanyRepresentativeName"),
            new SqlColumnInfo("CompanyTelephone"),
            new SqlColumnInfo("CompanyTradingName"),
            new SqlColumnInfo("CompanyWillPayBills"),
            new SqlColumnInfo("Completed"),
            new SqlColumnInfo("CompletedDate"),
            new SqlColumnInfo("ConfirmationKey"),
            new SqlColumnInfo("Confirmed"),
            new SqlColumnInfo("ConfirmedDate"),
            new SqlColumnInfo("ConsentMessage"),
            new SqlColumnInfo("ContactAddressIsNotCompanyAddress"),
            new SqlColumnInfo("ContactId"),
            new SqlColumnInfo("ContactJobTitle"),
            new SqlColumnInfo("ContextKey"),
            new SqlColumnInfo("CopyToSender"),
            new SqlColumnInfo("CouncilDataId"),
            new SqlColumnInfo("CouncilId"),
            new SqlColumnInfo("CouncilName"),
            new SqlColumnInfo("Councils"),
            new SqlColumnInfo("Country"),
            new SqlColumnInfo("County"),
            new SqlColumnInfo("CreatedById"),
            new SqlColumnInfo("CreatedDate"),
            new SqlColumnInfo("CreditCardSurchargePercentage"),
            new SqlColumnInfo("CreditCheckScore"),
            new SqlColumnInfo("CreditCheckScoreReason"),
            new SqlColumnInfo("CreditCheckId"),
            new SqlColumnInfo("CreditCheckOnlyDefault"),
            new SqlColumnInfo("CreditCheckProvider"),
            new SqlColumnInfo("CreditChecks"),
            new SqlColumnInfo("CurrentAddress"),
            new SqlColumnInfo("CustomDocPublic"),
            new SqlColumnInfo("DailyPostcodeLimit"),
            new SqlColumnInfo("DataExtractedDate"),
            new SqlColumnInfo("DateAvailable"),
            new SqlColumnInfo("DateOfBirth"),
            new SqlColumnInfo("DateOfIncorporation"),
            new SqlColumnInfo("DateToBeCleaned"),
            new SqlColumnInfo("DeadlineReachedDate"),
            new SqlColumnInfo("DeclineCode"),
            new SqlColumnInfo("DefaultDepositScheme"),
            new SqlColumnInfo("DefaultSigningAuthority"),
            new SqlColumnInfo("DelayedSend"),
            new SqlColumnInfo("DelayProcessing"),
            new SqlColumnInfo("Deleted"),
            new SqlColumnInfo("Dependant"),
            new SqlColumnInfo("DepositAmount"),
            new SqlColumnInfo("DepositScheme"),
            new SqlColumnInfo("DepositSchemeAccountNo"),
            new SqlColumnInfo("DepositSchemeReferenceNo"),
            new SqlColumnInfo("DepositSchemeType"),
            new SqlColumnInfo("DepositType"),
            new SqlColumnInfo("Description"),
            new SqlColumnInfo("DesktopDetailViews"),
            new SqlColumnInfo("DesktopSummaryViews"),
            new SqlColumnInfo("DigestHa1Hash"),
            new SqlColumnInfo("DirectorEmail"),
            new SqlColumnInfo("DirectorName"),
            new SqlColumnInfo("DirectorNumber"),
            new SqlColumnInfo("DirectorTitle"),
            new SqlColumnInfo("Disabled"){IsBool = true},
            new SqlColumnInfo("DisableUpSaleAdverts"),
            new SqlColumnInfo("DisableSystemUpSaleAdverts"),
            new SqlColumnInfo("DisplayAddress"),
            new SqlColumnInfo("DocumentDate"),
            new SqlColumnInfo("DocumentEpcRequiredProperty"){IsBool = true},
            new SqlColumnInfo("DocumentGscRequiredProperty"){IsBool = true},
            new SqlColumnInfo("DocumentId"),
            new SqlColumnInfo("DocumentIdRequiredGuarantor"){IsBool = true},
            new SqlColumnInfo("DocumentIdRequiredLandlord"){IsBool = true},
            new SqlColumnInfo("DocumentIdRequiredTenant"){IsBool = true},
            new SqlColumnInfo("DocumentLocation"),
            new SqlColumnInfo("DocumentLocationItp"),
            new SqlColumnInfo("DocumentLocationHttp"),
            new SqlColumnInfo("DocumentName"),
            new SqlColumnInfo("DocumentOwnershipRequiredLandlord"){IsBool = true},
            new SqlColumnInfo("DocumentPhotoIdRequiredGuarantor"){IsBool = true},
            new SqlColumnInfo("DocumentPhotoIdRequiredLandlord"){IsBool = true},
            new SqlColumnInfo("DocumentPhotoIdRequiredTenant"){IsBool = true},
            new SqlColumnInfo("DocumentReference"),
            new SqlColumnInfo("DocumentResidenceRequiredGuarantor"){IsBool = true},
            new SqlColumnInfo("DocumentResidenceRequiredLandlord"){IsBool = true},
            new SqlColumnInfo("DocumentResidenceRequiredTenant"){IsBool = true},
            new SqlColumnInfo("DocumentRtrRequiredGuarantor"){IsBool = true},
            new SqlColumnInfo("DocumentRtrRequiredTenant"){IsBool = true},
            new SqlColumnInfo("DocumentsRecieved"){IsBool = true},
            new SqlColumnInfo("DocumentType"),
            new SqlColumnInfo("DocuSignEnvolopesRecievedTo"),
            new SqlColumnInfo("DocusignIntegratorKey"),
            new SqlColumnInfo("DocusignPassword"),
            new SqlColumnInfo("DocusignUser"),
            new SqlColumnInfo("DoNotEmailAdditionalLandlords"){IsBool = true},
            new SqlColumnInfo("DoNotSendRenewalReminders"){IsBool = true},
            new SqlColumnInfo("DoYouSelfAssess"){IsBool = true},
            new SqlColumnInfo("DSS"),
            new SqlColumnInfo("DSSGuarantorRequired"){IsBool = true},
            new SqlColumnInfo("DueAgencyPaymentOverride"),
            new SqlColumnInfo("DueDateOverride"),
            new SqlColumnInfo("Duration"),
            new SqlColumnInfo("EchoBucketOverride"),
            new SqlColumnInfo("Economy7"),
            new SqlColumnInfo("ELettingDocument"),
            new SqlColumnInfo("ELettingDocumentId"),
            new SqlColumnInfo("ELettingDocumentNotes"),
            new SqlColumnInfo("Email"),
            new SqlColumnInfo("EmailAttachment"),
            new SqlColumnInfo("EmailAttachmentId"),
            new SqlColumnInfo("EmailBody"),
            new SqlColumnInfo("EmailDeliveryNotificationType"),
            new SqlColumnInfo("EmailDeliveryNotificationTypeDate"),
            new SqlColumnInfo("EmailQueueItemId"),
            new SqlColumnInfo("EmailQueueItems"),
            new SqlColumnInfo("EmailReference"),
            new SqlColumnInfo("EmailReminderId"),
            new SqlColumnInfo("EmailReminders"),
            new SqlColumnInfo("EmailSent"),
            new SqlColumnInfo("EmailSubject"),
            new SqlColumnInfo("EmailTemplate"),
            new SqlColumnInfo("EmailType"),
            new SqlColumnInfo("EmailWhenKeyHandoverAllowed"),
            new SqlColumnInfo("EmailWhenReservationFeesPaid"),
            new SqlColumnInfo("EmployeeNumber"),
            new SqlColumnInfo("EmploymentAddress"),
            new SqlColumnInfo("EmploymentContact"),
            new SqlColumnInfo("EmploymentIsLikelyToChange"),
            new SqlColumnInfo("EmploymentReferenceId"),
            new SqlColumnInfo("EmploymentReferences"),
            new SqlColumnInfo("EmploymentStatus"),
            new SqlColumnInfo("Enabled") {IsBool = true},
            new SqlColumnInfo("EnableMiDashboards"){IsBool = true},
            new SqlColumnInfo("EncryptedAccountName"),
            new SqlColumnInfo("EncryptedAccountNumber"),
            new SqlColumnInfo("EncryptedBankName"),
            new SqlColumnInfo("EncryptedBenefitsTaxCredits"),
            new SqlColumnInfo("EncryptedCourtDecreeDescription"),
            new SqlColumnInfo("EncryptedNiNumber"),
            new SqlColumnInfo("EncryptedPassportNumber"),
            new SqlColumnInfo("EncryptedSalary"),
            new SqlColumnInfo("EncryptedSavings"),
            new SqlColumnInfo("EncryptedSortCode"),
            new SqlColumnInfo("EncryptedUsageKey"),
            new SqlColumnInfo("EndDate"),
            new SqlColumnInfo("EnteredAsNet") {IsBool = true},
            new SqlColumnInfo("EntityType"),
            new SqlColumnInfo("ErrorClass"),
            new SqlColumnInfo("ErrorCount"),
            new SqlColumnInfo("ErrorMessage"),
            new SqlColumnInfo("ErrorMethod"),
            new SqlColumnInfo("ErrorSource"),
            new SqlColumnInfo("ESignCompleteDate"),
            new SqlColumnInfo("ESignRequestDate"),
            new SqlColumnInfo("Established"),
            new SqlColumnInfo("EventDate"),
            new SqlColumnInfo("EventLevel"),
            new SqlColumnInfo("EventMessage"),
            new SqlColumnInfo("EventName"),
            new SqlColumnInfo("EventType"),
            new SqlColumnInfo("ExcludesVat") {IsBool = true},
            new SqlColumnInfo("ExemptFromLandlordLicence"),
            new SqlColumnInfo("ExpectedGuarantorCount"),
            new SqlColumnInfo("ExpectedTenantCount"),
            new SqlColumnInfo("ExpiryDateOverride"),
            new SqlColumnInfo("ExternalId"),
            new SqlColumnInfo("ExternalStatus"),
            new SqlColumnInfo("ExternalStatusDetail"),
            new SqlColumnInfo("ExternalSystem"),
            new SqlColumnInfo("ExternalSystemReference"),
            new SqlColumnInfo("ExternalTenancyQueueItemId"),
            new SqlColumnInfo("ExternalTenancyQueueItems"),
            new SqlColumnInfo("Extracted"){IsBool = true},
            new SqlColumnInfo("ExtractedBy"),
            new SqlColumnInfo("ExtractedDate"),
            new SqlColumnInfo("FailureCount"),
            new SqlColumnInfo("FeesDue"),
            new SqlColumnInfo("FeesPaid") {IsBool = true},
            new SqlColumnInfo("FeesPaidDate"),
            new SqlColumnInfo("FilenameOveride"),
            new SqlColumnInfo("FileVirusStatus"),
            new SqlColumnInfo("FileVirusStatusDate"),
            new SqlColumnInfo("FirstDataAccount"),
            new SqlColumnInfo("FirstDataSecret"),
            new SqlColumnInfo("FirstListedDate"),
            new SqlColumnInfo("FirstName"),
            new SqlColumnInfo("FixedSystemFees"),
            new SqlColumnInfo("FixedSystemFeesDefault"),
            new SqlColumnInfo("FixFloEnabled"),
            new SqlColumnInfo("FixFloIdentifier"),
            new SqlColumnInfo("FixFloPassword"),
            new SqlColumnInfo("Floors"),
            new SqlColumnInfo("FooterTextOverride"),
            new SqlColumnInfo("ForgetMeDate"),
            new SqlColumnInfo("ForwardingEmailAddress"),
            //new SqlColumnInfo( //"From"),
                new SqlColumnInfo("FromDisplayName"),
                new SqlColumnInfo("Furnished"),
                new SqlColumnInfo("GasSupplied"),
                new SqlColumnInfo("GaTrackingId"),
                new SqlColumnInfo("Gender"),
                new SqlColumnInfo("GeneratedDoc1"),
                new SqlColumnInfo("GeneratedDoc1Name"),
                new SqlColumnInfo("GeneratedDoc2"),
                new SqlColumnInfo("GeneratedDoc2Name"),
                new SqlColumnInfo("GeneratedDocumentType"),
                new SqlColumnInfo("GrossAmount"),
                new SqlColumnInfo("GrossAmountOverride"),
                new SqlColumnInfo("GrossPrice"),
                new SqlColumnInfo("GrossProfit"),
                new SqlColumnInfo("GroupCount"),
                new SqlColumnInfo("GroupName"),
                new SqlColumnInfo("Guarantor_PropertyUserId"),
                new SqlColumnInfo("GuarantorAccept"),
                new SqlColumnInfo("GuarantorDoc"),
                new SqlColumnInfo("GuarantorGroup"),
                new SqlColumnInfo("GuarantorProduct"),
                new SqlColumnInfo("GuarantorRentMultiple"),
                new SqlColumnInfo("GuarantorRequired"),
                new SqlColumnInfo("GuarantorsRequiredForAllParties"),
                new SqlColumnInfo("GuarantorsRequiredForAllPartiesDefault"),
                new SqlColumnInfo("GuarantorTenants"),
                new SqlColumnInfo("GuarantorTerm"),
                new SqlColumnInfo("Handlers"),
                new SqlColumnInfo("HasBuildingsInsurance"),
                new SqlColumnInfo("HasCcjLetterOfSatisfaction"),
                new SqlColumnInfo("HasContentsInsurance"),
                new SqlColumnInfo("HasCurrentAccount"),
                new SqlColumnInfo("HasDependents"),
                new SqlColumnInfo("HasFireEscape"),
                new SqlColumnInfo("HasForwardingAddress"),
                new SqlColumnInfo("Hash"),
                new SqlColumnInfo("HasInviteBeenSent") {IsBool = true},
                new SqlColumnInfo("HasMoveInDate"),
                new SqlColumnInfo("HasOtherIncomeSources"),
                new SqlColumnInfo("HasOtherNames"),
                new SqlColumnInfo("HasOutstandingCcjOrAdverseCredit"),
                new SqlColumnInfo("HasPets"),
                new SqlColumnInfo("HasRentDeposit"),
                new SqlColumnInfo("HasSoftFurnishingFireLabels"),
                new SqlColumnInfo("HasStandingOrderReminderBeenSent"),
                new SqlColumnInfo("HasUkDocumentation"),
                new SqlColumnInfo("HeatingTypes"),
                new SqlColumnInfo("HelpLink"),
                new SqlColumnInfo("HelpLinkId"),
                new SqlColumnInfo("HidePropertyAdvertSection"),
                new SqlColumnInfo("HoldingDepositPaid"),
                new SqlColumnInfo("HomeletAsn"),
                new SqlColumnInfo("HomeletSecret"),
                new SqlColumnInfo("HomeletUser"),
                new SqlColumnInfo("HomeTel"),
                new SqlColumnInfo("HostedUrl"),
                new SqlColumnInfo("HostingOrganisationId"),
                new SqlColumnInfo("HoursTillEmailRepeat"),
                new SqlColumnInfo("HoursTillTrigger"),
                new SqlColumnInfo("HowToRentNotRequired"),
                new SqlColumnInfo("HtmlMessage"),
                new SqlColumnInfo("Id"),
                new SqlColumnInfo("IdCheckAutomaticallyPassed"),
                new SqlColumnInfo("IdCheckCount"),
                new SqlColumnInfo("IdCheckDate"),
                new SqlColumnInfo("IdCheckStatus"),
                new SqlColumnInfo("IdCheckType"),
                new SqlColumnInfo("ImmigrationStatus"),
                new SqlColumnInfo("ImpairedCredit"),
                new SqlColumnInfo("Inactive"),
                new SqlColumnInfo("IncludeInDocuSignPack") {IsBool = true},
                new SqlColumnInfo("Inclusive"),
                new SqlColumnInfo("Income"),
                new SqlColumnInfo("InfoUrl"),
                new SqlColumnInfo("InnerErrorMessage"),
                new SqlColumnInfo("InitialsOnly"){IsBool = true},
                new SqlColumnInfo("InspectionDate"),
                new SqlColumnInfo("InspectionFrequency"),
                new SqlColumnInfo("InspectionId"),
                new SqlColumnInfo("InspectionNotifyGuarantorsDefault"),
                new SqlColumnInfo("InspectionNotifyLandlordsDefault"),
                new SqlColumnInfo("InspectionNotifyTenantsDefault"),
                new SqlColumnInfo("Inspections"),
                new SqlColumnInfo("InspectionServiceProvider"),
                new SqlColumnInfo("InspectionType"),
                new SqlColumnInfo("InterestChangedDate"),
                new SqlColumnInfo("InternalCode"),
                new SqlColumnInfo("InternalSubType"),
                new SqlColumnInfo("InternalType"),
                new SqlColumnInfo("IsArchived"){IsBool = true},
                new SqlColumnInfo("IsAutoProceed"){IsBool = true},
                new SqlColumnInfo("IsBooked"){IsBool = true},
                new SqlColumnInfo("IsCancelled"){IsBool = true},
                new SqlColumnInfo("IsCompany"){IsBool = true},
                new SqlColumnInfo("IsCompleted"){IsBool = true},
                new SqlColumnInfo("IsCreditCheckOnly"){IsBool = true},
                new SqlColumnInfo("IsDeleted"){IsBool = true},
                new SqlColumnInfo("IsEarlyTermination"){IsBool = true},
                new SqlColumnInfo("IsElectric"){IsBool = true},
                new SqlColumnInfo("IsExpired"){IsBool = true},
                new SqlColumnInfo("IsFutureEmployment"){IsBool = true},
                new SqlColumnInfo("IsGas"){IsBool = true},
                new SqlColumnInfo("IsHosted"){IsBool = true},
                new SqlColumnInfo("IsHostingActive"){IsBool = true},
                new SqlColumnInfo("IsInterested"){IsBool = true},
                new SqlColumnInfo("IsLocked"){IsBool = true},
                new SqlColumnInfo("IsLotsOfLeave"){IsBool = true},
                new SqlColumnInfo("IsMandatory"){IsBool = true},
                new SqlColumnInfo("IsManualTenancyCheck"){IsBool = true},
                new SqlColumnInfo("IsMeetTenant"){IsBool = true},
                new SqlColumnInfo("IsMostRecent"){IsBool = true},
                new SqlColumnInfo("IsOnProbation"){IsBool = true},
                new SqlColumnInfo("IsPrivate"){IsBool = true},
                new SqlColumnInfo("IsPrivateTenant"){IsBool = true},
                new SqlColumnInfo("IsRead"){IsBool = true},
                new SqlColumnInfo("IsRegisteringDeposit"){IsBool = true},
                new SqlColumnInfo("IsSmoker"){IsBool = true},
                new SqlColumnInfo("IsSubmittingAccounts"){IsBool = true},
                new SqlColumnInfo("IssueCategory"),
                new SqlColumnInfo("IsTenancyAgreement") {IsBool = true},
                new SqlColumnInfo("IsTenantPresent") {IsBool = true},
                new SqlColumnInfo("IsUkAddress") {IsBool = true},
                new SqlColumnInfo("IsVirtual") {IsBool = true},
                new SqlColumnInfo("IsWaste") {IsBool = true},
                new SqlColumnInfo("IsWater"){IsBool = true},
                new SqlColumnInfo("ItpTemplatePath"),
                new SqlColumnInfo("Iva"),
                new SqlColumnInfo("KapturAccessKey"),
                new SqlColumnInfo("KapturEnabled"),
                new SqlColumnInfo("KapturPartnerAccessKey"),
                new SqlColumnInfo("KapturPartnerEnabled"),
                new SqlColumnInfo("KapturPartnerUser"),
                new SqlColumnInfo("KapturUser"),
                new SqlColumnInfo("Key"),
                new SqlColumnInfo("KeyLocation"),
                new SqlColumnInfo("KeyReturnLocation"),
                new SqlColumnInfo("KeysRecievedDate"),
                new SqlColumnInfo("KeysRecievedRequested"),
                new SqlColumnInfo("LandlordAssociation"),
                new SqlColumnInfo("LandlordCanVerifyDocuments"),
                new SqlColumnInfo("LandlordConfirmMoveInMonies"),
                new SqlColumnInfo("LandlordDoc"),
                new SqlColumnInfo("LandlordGroup"),
                new SqlColumnInfo("LandlordOrganiseEpc"),
                new SqlColumnInfo("LandlordPackageFeePaymentType"),
                new SqlColumnInfo("LandlordProduct"),
                new SqlColumnInfo("LandlordsCanMakeReferenceDecisions"),
                new SqlColumnInfo("LandlordsPayAllDebits"),
                new SqlColumnInfo("LandlordTerm"),
                new SqlColumnInfo("LandlordWallMessagesReadToDate"),
                new SqlColumnInfo("Last4Digits"),
                new SqlColumnInfo("LastAuthenticationFailure"),
                new SqlColumnInfo("LastBatchEndTime"),
                new SqlColumnInfo("LastBatchRunDuration"),
                new SqlColumnInfo("LastBatchServer"),
                new SqlColumnInfo("LastBatchStartTime"),
                new SqlColumnInfo("LastBatchUpdate"),
                new SqlColumnInfo("LastCcjDate"),
                new SqlColumnInfo("LastError"),
                new SqlColumnInfo("LastExpiredDocumentsProcessed"),
                new SqlColumnInfo("LastFailureMessage"),
                new SqlColumnInfo("LastFailureTime"),
                new SqlColumnInfo("LastListedDate"),
                new SqlColumnInfo("LastName"),
                new SqlColumnInfo("LastPasswordChangeDate"),
                new SqlColumnInfo("LastPoscodeLookupDate"),
                new SqlColumnInfo("LastRunByUser"),
                new SqlColumnInfo("LastRunSkipped"),
                new SqlColumnInfo("LastRunSucceeded"),
                new SqlColumnInfo("LastTtsDataUpdate"),
                new SqlColumnInfo("LastViewedDate"),
                new SqlColumnInfo("LeadImageUrl"),
                new SqlColumnInfo("LegalMessage"),
                new SqlColumnInfo("LinkClicked"),
                new SqlColumnInfo("LinkClickedDate"),
                new SqlColumnInfo("LinkedUnDeclaredAddressesCount"),
                new SqlColumnInfo("LinkedUserId"),
                new SqlColumnInfo("Log"),
                new SqlColumnInfo("LogId"),
                new SqlColumnInfo("LoginDate"),
                new SqlColumnInfo("LookupId"),
                new SqlColumnInfo("Lookups"),
                new SqlColumnInfo("LookupValue"),
                new SqlColumnInfo("LotsOfLeaveReason"),
                new SqlColumnInfo("MachineName"),
                new SqlColumnInfo("MaintenanceItemExternalId"),
                new SqlColumnInfo("MaintenanceItemId"),
                new SqlColumnInfo("MaintenanceItems"),
                new SqlColumnInfo("MaintenanceReference"),
                new SqlColumnInfo("ManagementAppsLink"),
                new SqlColumnInfo("ManuallyLoaded"),
                new SqlColumnInfo("ManualPayment"),
                new SqlColumnInfo("MaritalStatus"),
                new SqlColumnInfo("MarketingType"),
                new SqlColumnInfo("Matched"),
                new SqlColumnInfo("MaxAddressLinks"),
                new SqlColumnInfo("MaximumCcjs"),
                new SqlColumnInfo("MaximumNoOfOccupants"),
                new SqlColumnInfo("Message"),
                new SqlColumnInfo("MessageChainId"),
                new SqlColumnInfo("MeterLocation"),
                new SqlColumnInfo("MeterReading"),
                new SqlColumnInfo("MeterReading2"),
                new SqlColumnInfo("MeterReadingDate"),
                new SqlColumnInfo("MeterReference"),
                new SqlColumnInfo("MiddleName"),
                new SqlColumnInfo("MigrationId"),
                new SqlColumnInfo("MiGroup"),
                new SqlColumnInfo("MinimumAgreementMonthsOverride"),
                new SqlColumnInfo("MinimumPartialPaymentOverride"),
                new SqlColumnInfo("Mobile"),
                new SqlColumnInfo("MobileAppsLink"),
                new SqlColumnInfo("MobileDetailViews"),
                new SqlColumnInfo("MobileSummaryViews"),
                new SqlColumnInfo("Model"),
                new SqlColumnInfo("ModelMethodName"),
                new SqlColumnInfo("MonthlyRent"),
                new SqlColumnInfo("MoveInDate"),
                new SqlColumnInfo("MoveInFeePaymentType"),
                new SqlColumnInfo("MoveInProcessed"),
                new SqlColumnInfo("MoveOutDateOverride"),
                new SqlColumnInfo("Name"),
                new SqlColumnInfo("Nationality"),
                new SqlColumnInfo("NewValue"),
                new SqlColumnInfo("NextAgencyPaymentRun"),
                new SqlColumnInfo("NextOfKin"),
                new SqlColumnInfo("NextOfKinAddress"),
                new SqlColumnInfo("NlgAccessKey"),
                new SqlColumnInfo("NlgEnabled"),
                new SqlColumnInfo("NlgUser"),
                new SqlColumnInfo("NoInventoryRequired"),
                new SqlColumnInfo("NominalCodeGroup"),
                new SqlColumnInfo("NominalCodeGroupDiscriminator"),
                new SqlColumnInfo("NominalCodeGroupDiscriminatorType"),
                new SqlColumnInfo("NominalCodeId"),
                new SqlColumnInfo("NominalCodes"),
                new SqlColumnInfo("NoBankPayments") {IsBool = true},
                new SqlColumnInfo("NonCompanyAddress"),
                new SqlColumnInfo("Note"),
                new SqlColumnInfo("NoteId"),
                new SqlColumnInfo("Notes"),
                new SqlColumnInfo("NoticeEndDate"),
                new SqlColumnInfo("NoticeOfCorrection"),
                new SqlColumnInfo("NotificationId"),
                new SqlColumnInfo("NotificationMethod"),
                new SqlColumnInfo("NotificationType"),
                new SqlColumnInfo("NotifyAgent"),
                new SqlColumnInfo("NotifyGuarantorsOveride"),
                new SqlColumnInfo("NotifyLandlordsOveride"),
                new SqlColumnInfo("NotifyProvider"),
                new SqlColumnInfo("NotifyTenantsOveride"),
                new SqlColumnInfo("NumberOfIdChecksBeforeRefer"),
                new SqlColumnInfo("NumCoAlarms"),
                new SqlColumnInfo("NumDependants"),
                new SqlColumnInfo("NumSmokeAlarms"),
                new SqlColumnInfo("ObtainCreditReports") {IsBool = true},
                new SqlColumnInfo("OccupancyLength"),
                new SqlColumnInfo("OccupantId"),
                new SqlColumnInfo("Occupants"),
                new SqlColumnInfo("OfflineTenancySigning") {IsBool = true},
                new SqlColumnInfo("OldEmail"),
                new SqlColumnInfo("OnProbationPeriod"),
                new SqlColumnInfo("OptionalItem"),
                new SqlColumnInfo("Order"),
                new SqlColumnInfo("Organisation"),
                new SqlColumnInfo("Organisation_OrganisationId"),
                new SqlColumnInfo("OrganisationAddress"),
                new SqlColumnInfo("OrganisationEmailPreferences"),
                new SqlColumnInfo("OrganisationGroup"),
                new SqlColumnInfo("OrganisationGroup_OrganisationGroupId"),
                new SqlColumnInfo("OrganisationGroup_OrganisationGroupId1"),
                new SqlColumnInfo("OrganisationGroupId"),
                new SqlColumnInfo("OrganisationGroupOrganisationGroups"),
                new SqlColumnInfo("OrganisationGroupOrganisations"),
                new SqlColumnInfo("OrganisationGroupUserId"),
                new SqlColumnInfo("OrganisationGroupUserRole"),
                new SqlColumnInfo("OrganisationGroupUsers"),
                new SqlColumnInfo("OrganisationHostedItemId"),
                new SqlColumnInfo("OrganisationHostedItems"),
                new SqlColumnInfo("OrganisationHostedItemType"),
                new SqlColumnInfo("OrganisationId"),
                new SqlColumnInfo("OrganisationLogo"),
                new SqlColumnInfo("OrganisationNotifications"),
                new SqlColumnInfo("OrganisationStatement"),
                new SqlColumnInfo("OrganisationStatementId"),
                new SqlColumnInfo("OrganisationStatus"),
                new SqlColumnInfo("OrganisationType"),
                new SqlColumnInfo("OrganisationUrl"),
                new SqlColumnInfo("OrganisationUser"),
                new SqlColumnInfo("OrganisationUserId"),
                new SqlColumnInfo("OrganisationUserType"),
                new SqlColumnInfo("OrganisationUserRole"),
                new SqlColumnInfo("OriginalPaymentId"),
                new SqlColumnInfo("OriginalUrl"),
                new SqlColumnInfo("OriginalValue"),
                new SqlColumnInfo("OtherForenames"),
                new SqlColumnInfo("OtherIncomeSourcesDescription"),
                new SqlColumnInfo("OtherIncomeSourcesTotal"),
                new SqlColumnInfo("OtherSurname"),
                new SqlColumnInfo("OutsideSpaceTypes"),
                new SqlColumnInfo("OutstandingCcjAdditional"),
                new SqlColumnInfo("OutstandingDocumentsRequested"),
                new SqlColumnInfo("OverrideSystemFees"),
                new SqlColumnInfo("OverrideSystemTimers"),
                new SqlColumnInfo("PageHash"),
                new SqlColumnInfo("PageNumber"),
                new SqlColumnInfo("ParkingTypes"),
                new SqlColumnInfo("PasswordHash"),
                new SqlColumnInfo("PaymentCollectionType"),
                new SqlColumnInfo("PaymentDate"),
                new SqlColumnInfo("PaymentId"),
                new SqlColumnInfo("PaymentItem_PaymentItemId"),
                new SqlColumnInfo("PaymentItemId"),
                new SqlColumnInfo("PaymentItems"),
                new SqlColumnInfo("PaymentItemTenancyProducts"),
                new SqlColumnInfo("Payments"),
                new SqlColumnInfo("PaymentScheduleSent"),
                new SqlColumnInfo("PaymentStatus"),
                new SqlColumnInfo("PaymentType"),
                new SqlColumnInfo("PaymentTypeOverride"),
                new SqlColumnInfo("PaymentUrl"),
                new SqlColumnInfo("PercentageAmount"),
                new SqlColumnInfo("PercentageAmountOverride"),
                new SqlColumnInfo("PercentageSystemFees"),
                new SqlColumnInfo("PercentageSystemFeesDefault"),
                new SqlColumnInfo("PerformanceDate"),
                new SqlColumnInfo("Permission"),
                new SqlColumnInfo("PetType"),
                new SqlColumnInfo("Position"),
                new SqlColumnInfo("PositionInCompany"),
                new SqlColumnInfo("Postcode"),
                new SqlColumnInfo("PostCodeData"),
                new SqlColumnInfo("PostCodeDataId"),
                new SqlColumnInfo("PostcodeLookupsPerformedToday"),
                new SqlColumnInfo("PostcodeTrimmed"),
                new SqlColumnInfo("PrePayment"),
                new SqlColumnInfo("PreRegisteredUser"),
                new SqlColumnInfo("PreRegistrationRequiresNoAuthorisation"),
                new SqlColumnInfo("PreventLandlordFeeEarnerEmails"),
                new SqlColumnInfo("PrivateInAws"),
                new SqlColumnInfo("PrivateInAwsFailed"),
                new SqlColumnInfo("PrivateMessageId"),
                new SqlColumnInfo("PrivateMessages"),
                new SqlColumnInfo("ProbationPeriod"),
                new SqlColumnInfo("ProceedingTenant") {IsBool = true},
                new SqlColumnInfo("ProceedToReferencing") {IsBool = true},
                new SqlColumnInfo("Processed") {IsBool = true},
                new SqlColumnInfo("ProcessedDate"),
                new SqlColumnInfo("ProductGroupType"),
                new SqlColumnInfo("ProductId"),
                new SqlColumnInfo("ProductReference"),
                new SqlColumnInfo("ProductReferenceIndex"),
                new SqlColumnInfo("ProductReferencePattern"),
                new SqlColumnInfo("Products"),
                new SqlColumnInfo("ProductSetupComplete") {IsBool = true},
                new SqlColumnInfo("ProductType"),
                new SqlColumnInfo("ProductVersion"),
                new SqlColumnInfo("Property"),
                new SqlColumnInfo("PropertyAdvertId"),
                new SqlColumnInfo("PropertyAdvertPerformanceData"),
                new SqlColumnInfo("PropertyAdvertPerformanceId"),
                new SqlColumnInfo("PropertyAdverts"),
                new SqlColumnInfo("PropertyBuiltPeriod"),
                new SqlColumnInfo("PropertyDocument"),
                new SqlColumnInfo("PropertyDocumentId"),
                new SqlColumnInfo("PropertyId"),
                new SqlColumnInfo("PropertyListingStatus"),
                new SqlColumnInfo("PropertyManagerEmail"),
                new SqlColumnInfo("PropertyManagerName"),
                new SqlColumnInfo("PropertyManagerTelephone"),
                new SqlColumnInfo("PropertyNotes"),
                new SqlColumnInfo("PropertyPicture"),
                new SqlColumnInfo("PropertyPictureId"),
                new SqlColumnInfo("PropertyRemovalReason"),
                new SqlColumnInfo("PropertyRoom"),
                new SqlColumnInfo("PropertyRoomId"),
                new SqlColumnInfo("PropertyStatus"),
                new SqlColumnInfo("PropertyStyle"),
                new SqlColumnInfo("PropertyType"),
                new SqlColumnInfo("PropertyUser"),
                new SqlColumnInfo("PropertyUserId"),
                new SqlColumnInfo("PropertyUserNotifications"),
                new SqlColumnInfo("PropertyUserType"),
                new SqlColumnInfo("PropertyUserTypeDiscriminator"),
                new SqlColumnInfo("Provider"),
                new SqlColumnInfo("ProviderEmail"),
                new SqlColumnInfo("ProviderId"),
                new SqlColumnInfo("Providers"),
                new SqlColumnInfo("ProviderSummary"),
                new SqlColumnInfo("ProviderType"),
                new SqlColumnInfo("Quantity"),
                new SqlColumnInfo("RaisedEventId"),
                new SqlColumnInfo("RaisedEvents"),
                new SqlColumnInfo("RateCardProduct"),
                new SqlColumnInfo("RealCubeIntegrationEnabled"),
                new SqlColumnInfo("ReCaptchaSecret"),
                new SqlColumnInfo("ReCaptchaSiteKey"),
                new SqlColumnInfo("Recipent_PropertyUserId"),
                new SqlColumnInfo("RecipientEmail"),
                new SqlColumnInfo("RecipientId"),
                new SqlColumnInfo("RecipientType"),
                new SqlColumnInfo("Reconciled"){IsBool = true},
                new SqlColumnInfo("ReconciledBy"),
                new SqlColumnInfo("ReconciledDate"),
                new SqlColumnInfo("RecordId"),
                new SqlColumnInfo("RecordsProcessed"),
                new SqlColumnInfo("RefereeContactAddress"),
                new SqlColumnInfo("ReferenceCheckCreditScore"),
                new SqlColumnInfo("ReferenceCheckInitialPass"),
                new SqlColumnInfo("ReferenceCheckReason"),
                new SqlColumnInfo("ReferenceCheckStatus"),
                new SqlColumnInfo("ReferenceCheckStatusDate"),
                new SqlColumnInfo("ReferenceCompleteNotificationSent"),
                new SqlColumnInfo("ReferenceMaximumCcjs"),
                new SqlColumnInfo("ReferenceMaximumLinkedAddresses"),
                new SqlColumnInfo("ReferenceNumber"),
                new SqlColumnInfo("ReferencePaymentDeadline"),
                new SqlColumnInfo("ReferencePaymentId"),
                new SqlColumnInfo("ReferenceProductGroup"),
                new SqlColumnInfo("ReferenceProvider"),
                new SqlColumnInfo("ReferenceType"),
                new SqlColumnInfo("ReferenceZeroRentShareTenants") {IsBool = true},
                new SqlColumnInfo("ReferenceZeroRentShareTenantsDefault"),
                new SqlColumnInfo("ReferencingStarted"),
                new SqlColumnInfo("RegisteredDate"),
                new SqlColumnInfo("RegisteredOrganisationName"),
                new SqlColumnInfo("RegistrationNumber"),
                new SqlColumnInfo("Rejected"),
                new SqlColumnInfo("RejectedDate"),
                new SqlColumnInfo("RejectedIp"),
                new SqlColumnInfo("RejectedTenant") {IsBool = true},
                new SqlColumnInfo("ReminderAction"),
                new SqlColumnInfo("ReminderType"),
                new SqlColumnInfo("RemindInspectionDueDays"),
                new SqlColumnInfo("RemoteId"),
                new SqlColumnInfo("RemoteIpAddress"),
                new SqlColumnInfo("RemoteStatusDate"),
                new SqlColumnInfo("RemoteUri"),
                new SqlColumnInfo("RenewalRequiresTenantChanges"),
                new SqlColumnInfo("RenewedFromTenancyId"),
                new SqlColumnInfo("RentAmount"),
                new SqlColumnInfo("RentAmountInAdvance"),
                new SqlColumnInfo("RentForFullTermPaidUpFront"),
                new SqlColumnInfo("RentFrequency"),
                new SqlColumnInfo("RentGuaranteeType"),
                new SqlColumnInfo("RentMultiple"),
                new SqlColumnInfo("RentRecievedAmount"),
                new SqlColumnInfo("RentRemainingAmount"),
                new SqlColumnInfo("RentShareOverride"),
                new SqlColumnInfo("RentWarrantyAllowed"),
                new SqlColumnInfo("ReportUrl"),
                new SqlColumnInfo("RequestXml"),
                new SqlColumnInfo("RequirePropertyPictures"){IsBool = true},
                new SqlColumnInfo("RequireReservationConfirmation") {IsBool = true},
                new SqlColumnInfo("RequiresCeasing"){IsBool = true},
                new SqlColumnInfo("RequiresFinancialReferences"){IsBool = true},
                new SqlColumnInfo("RequiresLandlordLicence"){IsBool = true},
                new SqlColumnInfo("RequiresReview"){IsBool = true},
                new SqlColumnInfo("RequiresTtsUpdate") {IsBool = true},
                new SqlColumnInfo("RequiresUpdate"){IsBool = true},
                new SqlColumnInfo("RequireSupplierEntry"),
                new SqlColumnInfo("ReservationFeePaymentType"),
                new SqlColumnInfo("ResetPasswordRequestDate"),
                new SqlColumnInfo("ResetPasswordToken"),
                new SqlColumnInfo("ResidencyStatus"),
                new SqlColumnInfo("RightMoveBranchId"),
                new SqlColumnInfo("RightMoveCertificatePassword"),
                new SqlColumnInfo("RightMoveCertificatePath"),
                new SqlColumnInfo("RightMoveNetworkId"),
                new SqlColumnInfo("RightMovePropertyExpiryPeriod"),
                new SqlColumnInfo("RightMoveRef"),
                new SqlColumnInfo("RightMoveUrl"),
                new SqlColumnInfo("RightToBeForgottenEmail"),
                new SqlColumnInfo("RmLeadsRecievedTo"),
                new SqlColumnInfo("RmStatsLastDownloaded"),
                new SqlColumnInfo("RoomType"),
                new SqlColumnInfo("RowVersion"),
                new SqlColumnInfo("Salt"),
                new SqlColumnInfo("Score"),
                new SqlColumnInfo("SearchId"),
                new SqlColumnInfo("SecondaryIdNotRequired") {IsBool = true},
                new SqlColumnInfo("SecurityKey"),
                new SqlColumnInfo("Sender_PropertyUserId"),
                new SqlColumnInfo("SendIfUserUnconfirmed"),
                new SqlColumnInfo("SendInspectionNotifications"),
                new SqlColumnInfo("SendLandlordEmailOnInitialInvite"),
                new SqlColumnInfo("SendStandingOrderReminderEmail"),
                new SqlColumnInfo("SendTenantInspectionReminderEmail"),
                new SqlColumnInfo("SendTenantInspectionReminderText"),
                new SqlColumnInfo("SendToQube") {IsBool = true},
                new SqlColumnInfo("SerialisedRequest"),
                new SqlColumnInfo("SerialisedRightMoveRequest"),
                new SqlColumnInfo("ServedNotice"),
                new SqlColumnInfo("ServedNoticeDate"),
                new SqlColumnInfo("ServiceType"),
                new SqlColumnInfo("SharedWall"),
                new SqlColumnInfo("ShortTradingName"),
                new SqlColumnInfo("ShowCoBranding"),
                new SqlColumnInfo("SignedOffDate"),
                new SqlColumnInfo("SignedAgreementOnSystem"),
                new SqlColumnInfo("SignedWelcomePackOnSystem"),
                new SqlColumnInfo("SigningAuthority"),
                new SqlColumnInfo("SignsAgreements") {IsBool = true},
                new SqlColumnInfo("SkipReferencing"),
                new SqlColumnInfo("SmokeAlarmOperatingType"),
                new SqlColumnInfo("SmsNotification"),
                new SqlColumnInfo("SmsQueueItem"),
                new SqlColumnInfo("SmsQueueItemId"),
                new SqlColumnInfo("SmsText"),
                new SqlColumnInfo("SortOrder"),
                new SqlColumnInfo("SpecialTermAgreed"),
                new SqlColumnInfo("SpecialTermId"),
                new SqlColumnInfo("SpecialTerms"),
                new SqlColumnInfo("SpecialTermText"),
                new SqlColumnInfo("SpecialTermType"),
                new SqlColumnInfo("SpecifiedLimitOfTenants"),
                new SqlColumnInfo("StandardFeeFixed"),
                new SqlColumnInfo("StandardFeePercentage"),
                new SqlColumnInfo("StartDate"),
                new SqlColumnInfo("StaffByPassIdCheck"),
                new SqlColumnInfo("Status"),
                new SqlColumnInfo("StudentsAllowed"),
                new SqlColumnInfo("StudentGuarantorRequired"),
                new SqlColumnInfo("SubDomain"),
                new SqlColumnInfo("Subject"),
                new SqlColumnInfo("Summary"),
                new SqlColumnInfo("SupervisorPassword"),
                new SqlColumnInfo("SupplierData_SupplierId"),
                new SqlColumnInfo("SupplierDataId"),
                new SqlColumnInfo("SupplierId"),
                new SqlColumnInfo("SupplierName"),
                new SqlColumnInfo("Suppliers"),
                new SqlColumnInfo("SupplierType"),
                new SqlColumnInfo("Surcharge"),
                new SqlColumnInfo("SystemGeneratedPassword"),
                new SqlColumnInfo("SystemSettings"),
                new SqlColumnInfo("SystemSettingsId"),
                new SqlColumnInfo("SystemVideos"),
                new SqlColumnInfo("SystemWideSetting") {IsBool = true},
                new SqlColumnInfo("TableName"),
                new SqlColumnInfo("Tag"),
                new SqlColumnInfo("TaskName"),
                new SqlColumnInfo("TaskType"),
                new SqlColumnInfo("TaxType"),
                new SqlColumnInfo("TaxTypeDefault"),
                new SqlColumnInfo("TCApiKey"),
                new SqlColumnInfo("TCApiToken"),
                new SqlColumnInfo("TcApplicationStatus"),
                new SqlColumnInfo("TcData"),
                new SqlColumnInfo("TcDetail"),
                new SqlColumnInfo("TcFinalReportDownloaded"){IsBool = true},
                new SqlColumnInfo("TcId"),
                new SqlColumnInfo("TcInitialReportDownloaded") {IsBool = true},
                new SqlColumnInfo("TcLastAttemptedDate"),
                new SqlColumnInfo("TcLastUpdate"),
                new SqlColumnInfo("TcLastUpdatedDate"),
                new SqlColumnInfo("TcProgressStatus"),
                new SqlColumnInfo("TcRecommendationStatus"),
                new SqlColumnInfo("TcReference"),
                new SqlColumnInfo("TcUpdateNeeded") {IsBool = true},
                new SqlColumnInfo("TcUrl"),
                new SqlColumnInfo("TCUser"),
                new SqlColumnInfo("TelephoneNumber"),
                new SqlColumnInfo("Tenancy"),
                new SqlColumnInfo("TenancyAgreement"),
                new SqlColumnInfo("TenancyAgreementDocument"),
                new SqlColumnInfo("TenancyAgreementDocumentId"),
                new SqlColumnInfo("TenancyAgreementId"),
                new SqlColumnInfo("TenancyAgreementSigningZoneId"),
                new SqlColumnInfo("TenancyAgreementSigningZones"),
                new SqlColumnInfo("TenancyDocumentToAttach"),
                new SqlColumnInfo("TenancyId"),
                new SqlColumnInfo("TenancyProduct_TenancyProductId"),
                new SqlColumnInfo("TenancyProductId"),
                new SqlColumnInfo("TenancyProducts"),
                new SqlColumnInfo("TenancyRemovalReason"),
                new SqlColumnInfo("TenancyStatus"),
                new SqlColumnInfo("TenancySupplierData"),
                new SqlColumnInfo("TenancySupplierDataId"),
                new SqlColumnInfo("Tenant_PropertyUserId"),
                new SqlColumnInfo("TenantDoc"),
                new SqlColumnInfo("TenantGroup"),
                new SqlColumnInfo("TenantOrganisationId"),
                new SqlColumnInfo("TenantProduct"),
                new SqlColumnInfo("TenantReferenceId"),
                new SqlColumnInfo("TenantReferences"),
                new SqlColumnInfo("TenantRentMultiple"),
                new SqlColumnInfo("TenantsAndRentShareConfirmed") {IsBool = true},
                new SqlColumnInfo("TenantsAndRentShareConfirmedDate"),
                new SqlColumnInfo("TenantTerm"),
                new SqlColumnInfo("TenantWallMessagesReadToDate"),
                new SqlColumnInfo("TenantWantsDetails"),
                new SqlColumnInfo("TenantWantsViewing"),
                new SqlColumnInfo("TenantsByPassIdCheck"){IsBool = true},
                new SqlColumnInfo("Tenure"),
                new SqlColumnInfo("TermId"),
                new SqlColumnInfo("Terms"),
                new SqlColumnInfo("TermType"),
                new SqlColumnInfo("TextAnchor"),
                new SqlColumnInfo("TimeWithBankMonths"),
                new SqlColumnInfo("TimeWithBankYears"),
                new SqlColumnInfo("Title"),
                new SqlColumnInfo("TitleOverride"),
                new SqlColumnInfo("To"),
                new SqlColumnInfo("TrackableLinkId"),
                new SqlColumnInfo("TrackableLinks"),
                new SqlColumnInfo("TrackableLinkType"),
                new SqlColumnInfo("TrackingId"),
                new SqlColumnInfo("TradingName"),
                new SqlColumnInfo("TransactionType"),
                new SqlColumnInfo("TriggerData"),
                new SqlColumnInfo("TrustPilotBusinessId"),
                new SqlColumnInfo("TrustPilotTemplateId"),
                new SqlColumnInfo("TtsBroadband"){IsBool = true},
                new SqlColumnInfo("TtsCouncilId"),
                new SqlColumnInfo("TtsEnabled") {IsBool = true},
                new SqlColumnInfo("TtsEnergy"){IsBool = true},
                new SqlColumnInfo("TtsId"),
                new SqlColumnInfo("TtsInsurance"){IsBool = true},
                new SqlColumnInfo("TtsLinkedDate"),
                new SqlColumnInfo("TtsPassword"),
                new SqlColumnInfo("TtsPasswordVersion5"),
                new SqlColumnInfo("TtsStatus"),
                new SqlColumnInfo("TtsSupplierId"),
                new SqlColumnInfo("TtsUser"),
                new SqlColumnInfo("TtsUserVersion5"),
                new SqlColumnInfo("TxAuthNo"),
                new SqlColumnInfo("TxReference"),
                new SqlColumnInfo("Type"),
                new SqlColumnInfo("UnDeclaredAddress"),
                new SqlColumnInfo("UnitGrossAmount"),
                new SqlColumnInfo("UnitTaxAmount"),
                new SqlColumnInfo("UpdatedById"),
                new SqlColumnInfo("UpdatedDate"),
                new SqlColumnInfo("UploadedByUserId"),
                new SqlColumnInfo("UpSaleProductAdvertType"),
                new SqlColumnInfo("UpSaleProductCategory"),
                new SqlColumnInfo("UpSaleProductGroupId"),
                new SqlColumnInfo("UpSaleProductGroups"),
                new SqlColumnInfo("UpSaleProductGroupType"),
                new SqlColumnInfo("UpSaleProductId"),
                new SqlColumnInfo("UpSaleProductPreferences"),
                new SqlColumnInfo("UpSaleProductPreferencesId"),
                new SqlColumnInfo("UpSaleProductProceedButtonType"),
                new SqlColumnInfo("UpSaleProducts"),
                new SqlColumnInfo("Url"),
                new SqlColumnInfo("UsageKey"),
                new SqlColumnInfo("UseAgencyDefaultDepositScheme") {IsBool = true},
                new SqlColumnInfo("UseAmountOrPercentage"),
                new SqlColumnInfo("UseAmountOrPercentageOverride"),
                new SqlColumnInfo("UseAttachmentsForMoveInPack"),
                new SqlColumnInfo("UseDefaultProductSet") {IsBool = true},
                new SqlColumnInfo("UseLandlordBankAccount"),
                new SqlColumnInfo("UseLexelleProducts"),
                new SqlColumnInfo("UseOwnDocusignAccount") {IsBool = true},
                new SqlColumnInfo("User"),
                new SqlColumnInfo("UserAgent"),
                new SqlColumnInfo("UserAssociation"),
                new SqlColumnInfo("UserFullName"),
                new SqlColumnInfo("UserHasBeenPreRegistered"),
                new SqlColumnInfo("UserHostAddress"),
                new SqlColumnInfo("UserId"),
                new SqlColumnInfo("UserIsDirector"),
                new SqlColumnInfo("UserLoginAuditId"),
                new SqlColumnInfo("UserLoginAudits"),
                new SqlColumnInfo("UserNotes"),
                new SqlColumnInfo("UserTermId"),
                new SqlColumnInfo("UserTerms"),
                new SqlColumnInfo("UserType"),
                new SqlColumnInfo("UserTypeIndex"),
                new SqlColumnInfo("UtilitiesRecievedAmount"),
                new SqlColumnInfo("Value"),
                new SqlColumnInfo("VatDefault") {IsBool = true},
                new SqlColumnInfo("VatNumber"),
                new SqlColumnInfo("VendorTxCode"),
                new SqlColumnInfo("VerbType"),
                new SqlColumnInfo("VerificationState"),
                new SqlColumnInfo("VerifiedByUserId"),
                new SqlColumnInfo("VerifiedDate"),
                new SqlColumnInfo("Version"),
                new SqlColumnInfo("Vouchers"),
                new SqlColumnInfo("VideoCode"),
                new SqlColumnInfo("VideoId"),
                new SqlColumnInfo("VpsTxId"),
                new SqlColumnInfo("WallMessageId"),
                new SqlColumnInfo("WallMessages"),
                new SqlColumnInfo("WallMessagesReadToDate"),
                new SqlColumnInfo("WallMessageType"),
                new SqlColumnInfo("WallType"),
                new SqlColumnInfo("WantsQuote"),
                new SqlColumnInfo("WasEverBankrupt"),
                new SqlColumnInfo("WaterStopcockLocation"),
                new SqlColumnInfo("WelcomePackItemId"),
                new SqlColumnInfo("WelcomePackItems"),
                new SqlColumnInfo("WorkingDaysToCompleteReferencePayment"),
                new SqlColumnInfo("WorkingDaysToCompleteReferencePaymentOverride"),
                new SqlColumnInfo("WorkingDaysToCompleteTenancyAgreement"),
                new SqlColumnInfo("WorkingDaysToCompleteTenancyAgreementOverride"),
                new SqlColumnInfo("WorkTel"),
                new SqlColumnInfo("XPosition"),
                new SqlColumnInfo("XSize"),
                new SqlColumnInfo("YPosition"),
                new SqlColumnInfo("YSize"), 


        };
        #endregion

        public static List<SqlColumnInfo> ObjectInfo
        {
            get { return _objectInfo; }
        }
    }
}
